const { PrismaClient } = require('@prisma/client')
require('dotenv').config()

function sleep(ms) {
  return new Promise((res) => setTimeout(res, ms))
}

// Append connection_limit=1 to DATABASE_URL for PrismaClient
const rawDatabaseUrl = process.env.DATABASE_URL || ''
const dbUrl = rawDatabaseUrl.includes('connection_limit=1')
  ? rawDatabaseUrl
  : rawDatabaseUrl + (rawDatabaseUrl.includes('?') ? '&' : '?') + 'connection_limit=1'

const prisma = new PrismaClient({ datasources: { db: { url: dbUrl } } })

async function fetchSurah(surahNumber, attempt = 1) {
  const url = `https://api.quran.com/api/v4/quran/verses/uthmani?chapter_number=${surahNumber}`
  try {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`)
    const data = await res.json()
    return data.verses || []
  } catch (err) {
    if (attempt <= 5) {
      console.warn(`Fetch surah ${surahNumber} failed (attempt ${attempt}): ${err.message}. Retrying in 1s...`)
      await sleep(1000)
      return fetchSurah(surahNumber, attempt + 1)
    }
    throw err
  }
}

async function upsertAyah(ayah) {
  // Normalize fields with fallbacks for different API shapes
  let surahId = ayah.chapter_id ?? ayah.chapter_number ?? (ayah.chapter && ayah.chapter.id) ?? null
  let numberInSurah = ayah.verse_number ?? ayah.verse_number_in_chapter ?? ayah.verse_number ?? null

  // Some responses include `verse_key` like "114:6" — parse it when chapter/verse fields missing
  if ((!surahId || !numberInSurah) && ayah.verse_key) {
    const m = String(ayah.verse_key).split(':')
    if (m.length === 2) {
      const s = parseInt(m[0], 10)
      const v = parseInt(m[1], 10)
      if (!surahId) surahId = Number.isFinite(s) ? s : surahId
      if (!numberInSurah) numberInSurah = Number.isFinite(v) ? v : numberInSurah
    }
  }
  const numberInQuran = ayah.id ?? ayah.verse_id ?? null
  const textUthmani = ayah.text_uthmani ?? ayah.text ?? ''
  const textSimple = ayah.text_indopak ?? ayah.text_simple ?? ''
  const textArabic = textUthmani
  const page = ayah.page_number ?? ayah.page ?? 0
  const juz = ayah.juz_number ?? ayah.juz ?? 0
  const hizb = ayah.hizb_number ?? ayah.hizb ?? 0
  const ruku = ayah.ruku ?? 0
  const manzil = ayah.manzil ?? 0
  const sajda = !!(ayah.sajda && (ayah.sajda.recommended || ayah.sajda.obligatory || ayah.sajda))

  if (!surahId || !numberInSurah) {
    console.warn('Skipping ayah due to missing surahId or numberInSurah:', { id: numberInQuran, keys: Object.keys(ayah) })
    return null
  }

  const payload = {
    surahId,
    numberInSurah,
    numberInQuran,
    textArabic,
    textSimple,
    textUthmani,
    page,
    juz,
    hizb,
    ruku,
    manzil,
    sajda,
  }

  // Use composite unique where clause generated by Prisma for @@unique([surahId, numberInSurah])
  const where = { surahId_numberInSurah: { surahId: payload.surahId, numberInSurah: payload.numberInSurah } }

  const data = payload

  // Prisma upsert with composite unique
  return prisma.ayah.upsert({ where, update: data, create: data })
}

async function main() {
  console.log('Starting Quran seed: 114 surahs')
  try {
    for (let surah = 1; surah <= 114; surah++) {
      console.log(`Processing surah ${surah}...`)
      // Ensure the Surah row exists to satisfy foreign key constraints.
      try {
        await prisma.surah.upsert({
          where: { id: surah },
          update: {},
          create: {
            id: surah,
            nameArabic: '',
            nameEnglish: '',
            namePronunciation: '',
            revelation: '',
            ayahCount: 0,
            orderRevealed: 0,
            page: 0,
            juz: 0,
            ruku: 0,
          },
        })
      } catch (err) {
        console.warn(`Warning: could not ensure Surah ${surah} exists: ${err.message}`)
      }
      let verses
      try {
        verses = await fetchSurah(surah)
      } catch (err) {
        console.error(`Failed to fetch surah ${surah}:`, err)
        continue
      }

      for (const v of verses) {
        let attempts = 0
        while (true) {
          try {
            await upsertAyah(v)
            break
          } catch (err) {
            attempts++
            const message = err && err.message ? err.message : String(err)
            const isConnError = /connection|ECONN|terminate|closed|reset|timeout/i.test(message)
            if (attempts >= 5 || !isConnError) {
              console.error('Upsert failed for ayah', v.id, 'error:', message)
              break
            }
            console.warn(`Upsert retry ${attempts} for ayah ${v.id}: ${message}. Waiting 1s...`)
            await sleep(1000)
          }
        }
      }

      // wait 1 second between surahs to be gentle and allow connections to settle
      await sleep(1000)
    }
  } finally {
    await prisma.$disconnect()
  }
  console.log('Quran seed finished')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
